export enum STATUS {
  'CREATED' = 'CREATED',
  'IN_PROGRESS' = 'IN_PROGRESS',
  'COMPLETED' = 'COMPLETED'
}

export enum TYPE{
    PRODUCT='PRODUCT',
	DELIVERY='DELIVERY',
	OTHER='OTHER',
	BUILDER='BUILDER'
}
